include /usr/local/share/luggage/luggage.make
TITLE=Bind_to_Opendir_10_7
PACKAGEMAKER=/Applications/PackageMaker.app/Contents/MacOS/PackageMaker
REVERSE_DOMAIN=org.esl-education.Bind_to_Opendir_10_7
PAYLOAD=pack-script-postinstall \

