#!/bin/sh

# Script I use to bind a 10.7 client to Open Directory + SSL
# Use only on startup volume, in casper suite, 

# Define variables for path to executables
DSCONFIGLDAP="/usr/sbin/dsconfigldap"

# Define variables
ODM="nestor.esl.lan"

# Output variables
echo We will bind to $ODM


# Bind to the Open Directory Master
echo $DSCONFIGLDAP -vsemgx -a $ODM
$DSCONFIGLDAP -vsemgx -a $ODM << EOF
y
EOF

# done ! :)